# Generated by Django 5.2.1 on 2025-10-16 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('frame_count', models.IntegerField(default=0)),
                ('video_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('completed', 'Completed'), ('processing', 'Processing')], default='recording', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('frame_number', models.IntegerField()),
                ('pose_data', models.JSONField()),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='climber.sessionrecording')),
            ],
            options={
                'ordering': ['frame_number'],
                'indexes': [models.Index(fields=['session', 'frame_number'], name='climber_ses_session_5dbf77_idx')],
            },
        ),
    ]
