# Generated by Django 5.2.1 on 2025-10-20 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0003_session_sessionrecording_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='height_mm',
            field=models.FloatField(default=3330.0, help_text='Wall height in millimeters'),
        ),
        migrations.AddField(
            model_name='wall',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='svg_files/'),
        ),
        migrations.AddField(
            model_name='wall',
            name='width_mm',
            field=models.FloatField(default=2500.0, help_text='Wall width in millimeters'),
        ),
        migrations.CreateModel(
            name='WallCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('camera_matrix', models.JSONField(default=dict, help_text='3x3 camera intrinsic matrix')),
                ('distortion_coeffs', models.JSONField(default=list, help_text='Camera distortion coefficients')),
                ('perspective_transform', models.JSONField(default=dict, help_text='3x3 perspective transformation matrix')),
                ('aruco_markers', models.JSONField(default=dict, help_text='ArUco marker positions and IDs')),
                ('aruco_dictionary', models.CharField(default='DICT_4X4_50', max_length=50)),
                ('marker_size_meters', models.FloatField(default=0.1, help_text='Physical size of ArUco markers in meters')),
                ('calibration_image', models.ImageField(blank=True, null=True, upload_to='calibration_images/')),
                ('reprojection_error', models.FloatField(blank=True, help_text='Calibration accuracy measure', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='climber.wall')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
