# Generated by Django 5.2.1 on 2025-10-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0004_wall_height_mm_wall_svg_file_wall_width_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallcalibration',
            name='calibration_type',
            field=models.CharField(choices=[('aruco', 'ArUco Markers'), ('manual', 'Manual Points')], default='aruco', help_text='Type of calibration used', max_length=20),
        ),
        migrations.AddField(
            model_name='wallcalibration',
            name='manual_image_points',
            field=models.JSONField(blank=True, default=list, help_text='List of manually selected image points [(x1,y1), (x2,y2), ...]'),
        ),
        migrations.AddField(
            model_name='wallcalibration',
            name='manual_svg_points',
            field=models.JSONField(blank=True, default=list, help_text='List of corresponding SVG points [(x1,y1), (x2,y2), ...]'),
        ),
    ]
