# Generated by Django 5.2.1 on 2025-10-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0005_wallcalibration_calibration_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='wall_image',
            field=models.ImageField(blank=True, help_text='Wall image for calibration and overlay display', null=True, upload_to='wall_images/'),
        ),
    ]
