# Generated by Django 5.2.1 on 2025-10-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0006_add_wall_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallcalibration',
            name='calibration_type',
            field=models.CharField(choices=[('aruco', 'ArUco Markers'), ('manual', 'Manual Points'), ('draggable_svg', 'Draggable SVG')], default='aruco', help_text='Type of calibration used', max_length=20),
        ),
    ]
