# Generated by Django 5.2.1 on 2025-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0007_alter_wallcalibration_calibration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallcalibration',
            name='calibration_type',
            field=models.CharField(choices=[('aruco', 'ArUco Markers'), ('manual', 'Manual Points'), ('manual_points', 'Manual Point Calibration'), ('draggable_svg', 'Draggable SVG')], default='aruco', help_text='Type of calibration used', max_length=20),
        ),
    ]
