# Generated by Django 5.2.1 on 2025-10-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0008_alter_wallcalibration_calibration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Route data including holds and sequence'),
        ),
        migrations.DeleteModel(
            name='RoutePoint',
        ),
    ]
