# Generated by Django 5.2.1 on 2025-11-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0009_route_data_delete_routepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallcalibration',
            name='manual_image_height',
            field=models.FloatField(blank=True, help_text='Height of the image used for manual calibration', null=True),
        ),
        migrations.AddField(
            model_name='wallcalibration',
            name='manual_image_width',
            field=models.FloatField(blank=True, help_text='Width of the image used for manual calibration', null=True),
        ),
        migrations.AddField(
            model_name='wallcalibration',
            name='manual_svg_height',
            field=models.FloatField(blank=True, help_text='Height of the SVG used for manual calibration', null=True),
        ),
        migrations.AddField(
            model_name='wallcalibration',
            name='manual_svg_width',
            field=models.FloatField(blank=True, help_text='Width of the SVG used for manual calibration', null=True),
        ),
    ]
