# Generated by Django 5.2.1 on 2025-11-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0010_wallcalibration_manual_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallcalibration',
            name='overlay_image',
            field=models.ImageField(blank=True, help_text='Generated image with SVG overlay', null=True, upload_to='calibration_overlays/'),
        ),
        migrations.AlterField(
            model_name='wallcalibration',
            name='calibration_type',
            field=models.CharField(choices=[('aruco', 'ArUco Markers'), ('manual_points', 'Manual Point Calibration')], default='aruco', help_text='Type of calibration used', max_length=20),
        ),
    ]
