# Generated by Django 5.2.1 on 2025-11-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0011_wallcalibration_overlay_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallcalibration',
            name='manual_image_height',
        ),
        migrations.RemoveField(
            model_name='wallcalibration',
            name='manual_image_width',
        ),
        migrations.RemoveField(
            model_name='wallcalibration',
            name='manual_svg_height',
        ),
        migrations.RemoveField(
            model_name='wallcalibration',
            name='manual_svg_width',
        ),
    ]
