# Generated by Django 5.2.1 on 2025-11-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0012_remove_wallcalibration_manual_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallcalibration',
            name='hand_extension_percent',
            field=models.FloatField(default=20.0, help_text='Percentage to extend hand landmarks beyond the palm (0-100)'),
        ),
    ]
