# Generated by Django 5.2.1 on 2025-11-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0013_wallcalibration_hand_extension_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('wall_id', models.IntegerField(blank=True, null=True)),
                ('route_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'climber_celery_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
