# Generated by Django 5.2.1 on 2026-03-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climber', '0014_celerytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Difficulty level of the route', max_length=20, null=True),
        ),
    ]
